CREATE DATABASE COMPANY;
USE COMPANY;

CREATE TABLE EMPLOYEE (
ID INT PRIMARY KEY,
NAME VARCHAR(50),
MARKS INT,
GRADE VARCHAR(1),
CITY VARCHAR(20)
);

INSERT INTO EMPLOYEE (ID,NAME,MARKS,GRADE,CITY) VALUES
 (11,"AMIT",89,"B","PUNE"),
 (12,"ANIL",90,"A","DELHI"),
 (13,"ASHISH",96,"A","MUMBAI"),
 (14,"AYUSH",99,"A","VIZAG");
 
 select * from EMPLOYEE
where marks between 85 and 100;

SELECT * FROM EMPLOYEE
WHERE CITY IN ("DELHI","VIZAG");

SELECT * FROM EMPLOYEE
LIMIT 3;

SELECT * FROM EMPLOYEE
ORDER BY CITY ASC;

SELECT * FROM EMPLOYEE
ORDER BY MARKS DESC
LIMIT 3;

SELECT MIN(MARKS)
FROM EMPLOYEE;


SELECT COUNT(NAME)
FROM EMPLOYEE;

UPDATE EMPLOYEE
SET MARKS = 60
WHERE ID = 14;

SELECT * FROM EMPLOYEE;

ALTER TABLE EMPLOYEE
ADD COLUMN SALARY INT;

ALTER TABLE EMPLOYEE
ADD COLUMN AGE INT NOT NULL DEFAULT 19;

ALTER TABLE EMPLOYEE 
MODIFY COLUMN AGE VARCHAR(2);

ALTER TABLE EMPLOYEE
RENAME TO EMP;

ALTER TABLE EMP
RENAME TO EMPLOYEE;
